---

- block:
    - include_tasks: setup-build-dep-{{ ansible_pkg_mgr }}.yml

    - name: Clone pngquant source code
      ansible.builtin.git:
        repo: https://github.com/kornelski/pngquant.git
        dest: '{{ local_source_directory }}/pngquant'
        force: yes
        version: '{{ pngquant_version }}'
      register: _pngquant_git

    - name: Set pngquant build environment
      ansible.builtin.set_fact:
        pngquant_build_env: >
          {{ pngquant_build_cfg }}
          {{ _pngquant_git.after }}

    - name: Detect if pngquant must be reinstalled
      ansible.builtin.command:
        cat '{{ local_source_directory }}/pngquant.build.cfg'
      changed_when: >
        pngquant_build_env|trim != pngquant_build.stdout|default('')|trim
      check_mode: no
      failed_when: no
      register: pngquant_build

    - block:
        - name: Configure pngquant build process
          ansible.builtin.command:
            ./configure {{ pngquant_build_cfg }}
          args:
            chdir: '{{ local_source_directory }}/pngquant'

        - name: Build pngquant from source
          ansible.builtin.make:
            chdir: '{{ local_source_directory }}/pngquant'
            params:
              '--jobs': '{{ ansible_processor_cores }}'

        - name: Install pngquant from source
          ansible.builtin.make:
            chdir: '{{ local_source_directory }}/pngquant'
            target: install

        - name: Save build environment
          ansible.builtin.copy:
            content: '{{ pngquant_build_env }}'
            dest: '{{ local_source_directory }}/pngquant.build.cfg'
      when: pngquant_build is change
  become: yes
  tags: [pngquant, packages]
